-- Tabla orders
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    total DECIMAL(12, 2) NOT NULL,
    status VARCHAR(20) NOT NULL, 

    CONSTRAINT fk_order_user
        FOREIGN KEY (user_id)
        REFERENCES users (id) 
        ON DELETE RESTRICT
);

-- Tabla order_items
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_name VARCHAR(160) NOT NULL,
    quantity INT NOT NULL,
    price_at_purchase DECIMAL(12, 2) NOT NULL, 
    sub_total DECIMAL(12, 2) NOT NULL,

    -- Restricción de clave foránea
    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
        REFERENCES orders (id)
        ON DELETE CASCADE -- Si se elimina la orden, se eliminan sus items
);

-- Índices para optimizar la búsqueda de órdenes por usuario y la búsqueda de items por orden
CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);